#!/bin/bash

rm -r _minted-paper paper.aux paper.bbl paper.blg paper.log paper.out paper.synctex.gz build.log \
      appendix.aux paper.lof paper.lot paper.pdf paper.toc >> /dev/null 2>&1
for f in `find . -type f | grep .aux`; do rm $f; done

cp biblio/references.bib paper.bib

# Build the paper
echo "... building"
docker run --rm \
  --name latex \
  --entrypoint=/bin/bash \
  -v `pwd`/:/mnt/ \
  michaelsevilla/texlive:latest -c \
    "cd /mnt ; \
     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper; \
     bibtex paper; \
     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper; \
     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper;" &> build.log

ERR=$?
if [ $ERR != "0" ] ; then
  cat build.log
  echo "ERROR: $ERR"
  exit 1
fi

rm -r _minted-paper paper.aux paper.bbl paper.blg paper.log paper.out paper.synctex.gz build.log \
      appendix.aux paper.lof paper.lot paper.toc >> /dev/null 2>&1

for f in `find . -type f | grep .aux`; do rm $f; done

echo "SUCCESS"

